name: Deploy Staging Timro Ticket API

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            PROJECT_DIR="/var/www/sandbox.timroticket.com"
            REPO_URL="git@github.com:BandBTech/event_ticketing_backend.git"

            if [ -d "$PROJECT_DIR/.git" ]; then
              echo "🛠 Directory exists with git repo - Pulling latest code"
              cd $PROJECT_DIR
              GIT_SSH_COMMAND="ssh -i ~/.ssh/timroticket_backend_ed25519" git reset --hard
              GIT_SSH_COMMAND="ssh -i ~/.ssh/timroticket_backend_ed25519" git pull origin staging
            else
              echo "📁 Directory empty or no git repo - Cloning repository"
              rm -rf $PROJECT_DIR
              GIT_SSH_COMMAND="ssh -i ~/.ssh/timroticket_backend_ed25519" git clone -b staging $REPO_URL $PROJECT_DIR
              cd $PROJECT_DIR
            fi

            echo "🧹 Cleaning up old containers"
            docker compose down

            echo "📦 Rebuilding docker images"
            docker-compose up -d --build

            echo "✅ Deployment complete"
